import { describe, it, expect } from "vitest";
import { exec, type ExecException } from "child_process";

const APP_ENTRY = "node dist/index.js";

interface ExecResult {
  stdout: string;
  stderr: string;
  exitCode: number;
}

const execWithExitCode = (command: string): Promise<ExecResult> => {
  command = `${APP_ENTRY} ${command}`;
  return new Promise((resolve) => {
    exec(command, (error: ExecException | null, stdout: string, stderr: string) => {
      const result = {
        stdout,
        stderr,
        exitCode: error?.code ?? 0,
      };
      resolve(result);
    });
  });
};

describe(`${APP_ENTRY} base infos`, () => {
  it("should show help message", async () => {
    const { stdout, stderr, exitCode } = await execWithExitCode(`--help`);
    expect(exitCode).toBe(0);
    expect(stdout).toContain("Usage:");
    expect(stdout).toContain(APP_DESCRIPTION);
    expect(stderr).toBe("");
  });

  it("should run a command and return the correct version", async () => {
    const { stdout, stderr, exitCode } = await execWithExitCode(`--version`);
    expect(exitCode).toBe(0);
    expect(stdout).toContain(`${APP_NAME} ${APP_VERSION}`);
    expect(stderr).toBe("");
  });

  it("should fail with invalid command", async () => {
    const { exitCode } = await execWithExitCode(`unknown_command`);
    expect(exitCode).toBe(1);
  });
});

describe(`${APP_NAME} commands help`, () => {
  it(`"should show help message for diff"`, async () => {
    const { stdout, stderr, exitCode } = await execWithExitCode(`diff --help`);
    expect(exitCode).toBe(0);
    expect(stdout).toContain("Usage:");
    expect(stderr).toBe("");
  });

  it("should show help message for unused-prefs-userjs", async () => {
    const { stdout, stderr, exitCode } = await execWithExitCode(`unused-prefs-userjs --help`);
    expect(exitCode).toBe(0);
    expect(stdout).toContain("Usage:");
    expect(stdout).toContain("Identify unused preferences from your user.js file");
    expect(stderr).toBe("");
  });

  it("should show help message for default-prefs", async () => {
    const { stdout, stderr, exitCode } = await execWithExitCode(`default-prefs --help`);
    expect(exitCode).toBe(0);
    expect(stdout).toContain("Get a list of all default prefs");
    expect(stdout).toContain("Options:");
    expect(stderr).toBe("");
  });

  it("should show help message for default-prefs-userjs", async () => {
    const { stdout, stderr, exitCode } = await execWithExitCode(`default-prefs-userjs --help`);
    expect(exitCode).toBe(0);
    expect(stdout).toContain("Usage:");
    expect(stdout).toContain("Identify default preferences from your user.js file");
    expect(stderr).toBe("");
  });

  it("should run a command and return the correct version", async () => {
    const { stdout, stderr } = await execWithExitCode(`--version`);

    expect(stdout).toContain(`${APP_NAME} ${APP_VERSION}`);
    expect(stderr).toBe("");
  });
});

describe(`${APP_NAME} command validation`, () => {
  it("should fail when unused-prefs-userjs is called without arguments", async () => {
    const { exitCode, stderr } = await execWithExitCode(`unused-prefs-userjs`);
    expect(exitCode).toBe(1);
    expect(stderr).toContain("Identify unused preferences from your user.js file");
  });

  it("should fail when default-prefs-userjs is called without arguments", async () => {
    const { exitCode, stderr } = await execWithExitCode(`default-prefs-userjs`);
    expect(exitCode).toBe(1);
    expect(stderr).toContain("Identify default preferences from your user.js file");
  });

  it("should fail when diff is called with invalid version format", async () => {
    const { exitCode, stderr } = await execWithExitCode(`diff invalid notvalid`);
    expect(exitCode).toBe(1);
    expect(stderr).toContain("Compare the default preferences of two firefox versions");
  });

  it("should fail when diff is called without arguments", async () => {
    const { exitCode, stderr } = await execWithExitCode(`diff`);
    expect(exitCode).toBe(1);
    expect(stderr).toContain("Compare the default preferences of two firefox versions");
  });

  it("should accept valid version format for diff command", async () => {
    const { stderr } = await execWithExitCode(`diff 139.0 140.0 --help`);
    // If version format is accepted, it won't show usage error
    expect(stderr).not.toContain("Compare the default preferences of two firefox versions");
  });
});

describe(`${APP_NAME} command arguments`, () => {
  it("should accept --help flag for clean command", async () => {
    const { stdout, exitCode } = await execWithExitCode(`clean --help`);
    expect(exitCode).toBe(0);
    expect(stdout).toContain("Remove files generated by");
  });

  it("should handle multiple option flags correctly", async () => {
    const { stdout, exitCode } = await execWithExitCode(`diff --help --do-not-print-in-console`);
    expect(exitCode).toBe(0);
    expect(stdout).toContain("Compare the default preferences");
  });
});
